### ISSUE TITLE
AttributeError: module 'aiodbl' has no attribute 'Client'

### ISSUE THREAD

**Issue by 0xicl33n** [tilda/aiodbl#1]
Does not work.

    dbl = aiodbl.Client(token=statToken)
    async def post():
        await dbl.post(id=340354052715970563, count=len(bot.guilds))

    Traceback (most recent call last):
      File "bot.py", line 17, in <module>
        dbl = aiodbl.Client(token=statToken)
    AttributeError: module 'aiodbl' has no attribute 'Client'
    Unclosed client session
    client_session: <aiohttp.client.ClientSession object at 0x7fd0bd20c9e8>

Directory structure:

https://imgur.com/kbCAFj8

**Comment by tilda** [comment]
I don't know, maybe you can try it again? I just updated `__init__.py` to point to `aiodbl.client` file

**Comment by DoctorJew** [comment]
@tilda @0xicl33n Was able to fix the issue by changing `__init__.py` to contain:
```python
from .aiodbl.client import Client  # The first '.' references the current directory
```

**Comment by tilda** [comment]
Just thought about it and hopefully fixed it in latest commit

**Comment by tilda** [comment]
Assuming fixed, closing
